# Generated by Django 4.0.4 on 2022-05-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('opcion', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Config',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ("ccaa",models.CharField(max_length=30)),
                ("enlace",models.CharField(max_length=1000)),
                ('contador', models.IntegerField()),
            ],
            options={
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('tipoUS', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Quever',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('contacto', models.CharField(max_length=30)),
                ('foto', models.TextField()),
                ('idMunicipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.municipio')),
            ],
            options={
                'db_table': 'Quever',
            },
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('odio', models.FloatField(default=0)),
                ('odioNoticias', models.FloatField(default=0)),
                ('odioComentarios', models.FloatField(default=0)),
                ('Actualizar', models.DateTimeField(auto_now_add=True)),
                ('idMunicipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.municipio')),
            ],
            options={
                'db_table': 'Busqueda',
            },
        ),
    ]
